name: Janitor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  janitor:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      - name: Install ruff
        run: python -m pip install ruff

      - name: Install biome
        run: npm install -g @biomejs/biome

      - name: Run Janitor
        uses: janitor-sh/action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool: "ruff"
